name: AssetSizeMonitor

on:
  push:
    branches:
      - feat/asset-size-report

jobs:
  update-asset-sizes:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Build For Production
        run: yarn workspace ember-data ember build -e production
      - name: Generate Diff for Commit
        run: |
          mkdir -p tmp
          node ./bin/asset-size-tracking/generate-diff.js > tmp/diff.txt
      - name: Update Asset Sizes
        run: |
          node ./bin/asset-size-tracking/generate-analysis.js
      - name: Print Asset Sizes
        run: |
          node ./bin/asset-size-tracking/print-analysis.js > tmp/analysis.txt
      - name: Configure Git User
        run: |
          git config --local user.email "tomster@emberjs.com"
          git config --local user.name "AssetSize Tomster"
          git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git checkout -b asset-report/$GITHUB_SHA
      - name: Commit Report w/Analysis
        run: |
          diff_report=$(cat tmp/diff.txt)
          full_analysis=$(cat tmp/analysis.txt)
          git add bin/asset-size-tracking/current-data.json
          git commit -m "AssetSize Update for $GITHUB_SHA\n\n$diff_report\n\n$full_analysis"
      - name: Push Report
        run: |
          git push origin asset-report/$GITHUB_SHA
